name: mergeworks
description: "Merge magical items and unravel enchanting progression chains in this captivating puzzle game, blending strategic merges with delightful discoveries in a vibrant fantasy world."
publish_to: "none"
version: 1.0.0+18

environment:
  sdk: ^3.8.1

dependencies:
  connectivity_plus: ^7.0.0
  games_services: ^5.0.0
  google_mobile_ads: ^6.0.0
  in_app_purchase: ^3.0.0
  cloud_functions: ^6.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  provider: ^6.1.2
  go_router: ^16.3.0
  shared_preferences: ^2.5.3
  audioplayers: ^6.0.0
  confetti: 0.8.0
  firebase_core: ^4.3.0
  cloud_firestore: '>=5.5.0'
  firebase_auth: ^6.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/audio/FX/
    - assets/audio/Music/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/icon.jpg
  remove_alpha_ios: true
